"""Initial migration.

Revision ID: fb8f05fd5bf6
Revises: 
Create Date: 2024-11-30 11:15:38.900594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8f05fd5bf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.Enum('US', 'JP', name='market'), nullable=False),
    sa.Column('type', sa.Enum('STOCK', 'ETF', 'INDICES', 'FOREX', 'COMMODITIES', name='symboltype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=500), nullable=False),
    sa.Column('time_scale', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='timescale'), nullable=False),
    sa.Column('trigger_type', sa.Enum('ONCE', 'DAILY', name='triggertype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STOPPED', name='alertstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('suggested_action', sa.Enum('BUY', 'SELL', name='suggestedaction'), nullable=True),
    sa.Column('suggested_trading_type', sa.Enum('DAILY', 'SWING', 'LONG_TERM', name='suggestedtradingtype'), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('time_scale', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='timescale'), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbol_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('app_symbol', sa.String(length=50), nullable=False),
    sa.Column('api_provider', sa.Enum('YAHOO_FINANCE', name='apiprovider'), nullable=False),
    sa.Column('api_symbol', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('time_scale', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='timescale'), nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('alert_trigger')
    op.drop_table('technical_indicator')
    op.drop_table('symbol_mapping')
    op.drop_table('price')
    op.drop_table('alert')
    op.drop_table('symbol')
    # ### end Alembic commands ###
